### ISSUE TITLE
Issue with tree-view caused by this package (result: this package not working)

### ISSUE THREAD

**Issue by misterbridge** [wasikuss/temporary-root#2]
Please see: [tree-view/issues/1091](https://github.com/atom/tree-view/issues/1091#issuecomment-300427553)

**Comment by wasikuss** [comment]
fixed in [v1.0.2](https://github.com/wasikuss/temporary-root/releases/tag/v1.0.2) ;)

**Comment by misterbridge** [comment]
Thanks ! Works like a charm, I love it ;)
